# Generated by Django 5.1 on 2024-08-23 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('if_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='departamento',
            field=models.CharField(choices=[('Laboratorio', 'Laboratório'), ('Caen', 'Caen'), ('Pavilhao_novo', 'Pavilhão novo'), ('Pavilhao_velho', 'Pavilhão velho')], default='Laboratório', max_length=50),
            preserve_default=False,
        ),
    ]
