# Generated by Django 5.1 on 2024-08-23 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('if_app', '0002_usuario_departamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='departamento',
            field=models.CharField(choices=[('Laboratório', 'Laboratório'), ('Caen', 'Caen'), ('Pavilhão Novo', 'Pavilhão Novo'), ('Pavilhão Velho', 'Pavilhão Velho')], default='Laboratório', max_length=50),
        ),
    ]
