# Generated by Django 5.1 on 2024-08-20 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('if_dados', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chamado',
            name='tecnico',
        ),
        migrations.RemoveField(
            model_name='chamado',
            name='especialidade',
        ),
        migrations.AlterField(
            model_name='chamado',
            name='patrimonio',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='relato_tecnico',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='especialidade',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tecnico',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='HistoricoChamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_fechamento', models.DateField()),
                ('status', models.CharField(max_length=10)),
                ('relatorio', models.TextField(blank=True)),
                ('chamado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='if_dados.chamado')),
                ('tecnico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='if_dados.tecnico')),
            ],
        ),
        migrations.AddField(
            model_name='chamado',
            name='especialidade',
            field=models.ManyToManyField(blank=True, to='if_dados.especialidade'),
        ),
    ]
