# Generated by Django 5.1 on 2024-08-21 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('if_dados', '0002_remove_chamado_tecnico_remove_chamado_especialidade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chamado',
            name='equipamento',
        ),
        migrations.DeleteModel(
            name='Equipamento',
        ),
    ]
